export const Routes = [
 {
   "route_id": 2,
   "agency_id": 2,
   "route_short_name": "10",
   "route_long_name": "Tarján, Víztorony tér / Klinikák",
   "route_desc": "",
   "route_type": 11,
   "route_url": "",
   "route_color": "00CC00",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 6,
   "agency_id": 2,
   "route_short_name": "19",
   "route_long_name": "Makkosház / Tarján, Víztorony tér",
   "route_desc": "",
   "route_type": 11,
   "route_url": "",
   "route_color": "00CC00",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 7,
   "agency_id": 2,
   "route_short_name": "2",
   "route_long_name": "Európa liget / Szeged vasútállomás",
   "route_desc": "",
   "route_type": 0,
   "route_url": "",
   "route_color": "FFFF00",
   "route_text_color": "000000"
 },
 {
   "route_id": 8,
   "agency_id": 1,
   "route_short_name": "20",
   "route_long_name": "Petőfitelep, Fő tér / Alsóváros, Vadkerti tér",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 10,
   "agency_id": 1,
   "route_short_name": "21",
   "route_long_name": "Újpetőfitelep / Szeged vasútállomás",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 11,
   "agency_id": 2,
   "route_short_name": "3",
   "route_long_name": "Tarján / Vadaspark",
   "route_desc": "",
   "route_type": 0,
   "route_url": "",
   "route_color": "FFFF00",
   "route_text_color": "000000"
 },
 {
   "route_id": 12,
   "agency_id": 1,
   "route_short_name": "36",
   "route_long_name": "Honvéd tér / Kiskundorozsma",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 13,
   "agency_id": 2,
   "route_short_name": "3F",
   "route_long_name": "Tarján / Fonógyári út",
   "route_desc": "",
   "route_type": 0,
   "route_url": "",
   "route_color": "FFFF00",
   "route_text_color": "000000"
 },
 {
   "route_id": 14,
   "agency_id": 2,
   "route_short_name": "4",
   "route_long_name": "Tarján / Kecskés",
   "route_desc": "",
   "route_type": 0,
   "route_url": "",
   "route_color": "FFFF00",
   "route_text_color": "000000"
 },
 {
   "route_id": 15,
   "agency_id": 2,
   "route_short_name": "5",
   "route_long_name": "Körtöltés utca / Újszeged, Gyermekkórház",
   "route_desc": "",
   "route_type": 11,
   "route_url": "",
   "route_color": "00CC00",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 16,
   "agency_id": 1,
   "route_short_name": "60",
   "route_long_name": "Mars tér / Szőreg",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 17,
   "agency_id": 1,
   "route_short_name": "60Y",
   "route_long_name": "Mars tér / Szőreg",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 18,
   "agency_id": 1,
   "route_short_name": "64",
   "route_long_name": "Mars tér > Környezetgazdálkodási Kft. > Mars tér",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 20,
   "agency_id": 1,
   "route_short_name": "70",
   "route_long_name": "Mars tér / Újszeged, Füvészkert",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 21,
   "agency_id": 1,
   "route_short_name": "71",
   "route_long_name": "Szegedi Ipari Logisztikai Központ / Mars tér / Marostő, Katalin utca",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 22,
   "agency_id": 1,
   "route_short_name": "72",
   "route_long_name": "Szegedi Ipari Logisztikai Központ / Mars tér / Marostő, Erdélyi tér",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 23,
   "agency_id": 1,
   "route_short_name": "73",
   "route_long_name": "Mars tér / Tápé",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 24,
   "agency_id": 1,
   "route_short_name": "73Y",
   "route_long_name": "Mars tér / Tápé",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 27,
   "agency_id": 1,
   "route_short_name": "75",
   "route_long_name": "Mars tér / Kiskundorozsma",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 28,
   "agency_id": 1,
   "route_short_name": "76",
   "route_long_name": "Mars tér / Szentmihály",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 29,
   "agency_id": 1,
   "route_short_name": "77",
   "route_long_name": "Szeged vasútállomás / Baktó",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 30,
   "agency_id": 1,
   "route_short_name": "78",
   "route_long_name": "Napos út > Béketelep > Mars tér",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 31,
   "agency_id": 1,
   "route_short_name": "78A",
   "route_long_name": "Rókusi körút > Béketelep / Auchan > Mars tér",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 33,
   "agency_id": 1,
   "route_short_name": "79H",
   "route_long_name": "Mars tér / Fehértói halgazdaság",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 34,
   "agency_id": 1,
   "route_short_name": "7F",
   "route_long_name": "Mars tér / Sziksósfürdő",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 35,
   "agency_id": 2,
   "route_short_name": "8",
   "route_long_name": "Makkosház / Klinikák",
   "route_desc": "",
   "route_type": 11,
   "route_url": "",
   "route_color": "00CC00",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 36,
   "agency_id": 1,
   "route_short_name": "84",
   "route_long_name": "Makkosház / Újszeged, Gabonakutató",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 39,
   "agency_id": 1,
   "route_short_name": "90",
   "route_long_name": "Újszeged, Gabonakutató / Szeged vasútállomás",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 40,
   "agency_id": 1,
   "route_short_name": "90F",
   "route_long_name": "Petőfitelep, Fő tér / Vadaspark (Textilgyári út)",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 41,
   "agency_id": 1,
   "route_short_name": "90H",
   "route_long_name": "Lugas utca / Szegedi Ipari Logisztikai Központ",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 42,
   "agency_id": 1,
   "route_short_name": "77A",
   "route_long_name": "Mars tér / Baktó",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 44,
   "agency_id": 1,
   "route_short_name": "12",
   "route_long_name": "Tarján / Belvárosi temető / Tarján",
   "route_desc": "Temetői járat",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 45,
   "agency_id": 1,
   "route_short_name": "91E",
   "route_long_name": "Széchenyi tér > Újszeged > Szőreg > Mars tér",
   "route_desc": "Éjszakai járat",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 46,
   "agency_id": 1,
   "route_short_name": "92E",
   "route_long_name": "Széchenyi tér > Petőfitelep > Tarján",
   "route_desc": "Éjszakai járat",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 47,
   "agency_id": 1,
   "route_short_name": "93E",
   "route_long_name": "Széchenyi tér > Újrókus > Kiskundorozsma",
   "route_desc": "Éjszakai járat",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 48,
   "agency_id": 1,
   "route_short_name": "94E",
   "route_long_name": "Széchenyi tér > Alsóváros > Kecskéstelep",
   "route_desc": "Éjszakai járat",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 49,
   "agency_id": 1,
   "route_short_name": "24",
   "route_long_name": "Petőfitelep, Fő tér / Klebelsbergtelep",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 50,
   "agency_id": 1,
   "route_short_name": "32",
   "route_long_name": "Honvéd tér / Újszeged, víztorony",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 51,
   "agency_id": 1,
   "route_short_name": "67",
   "route_long_name": "Sziksósfürdő / Mars tér / Szőreg",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 52,
   "agency_id": 1,
   "route_short_name": "67Y",
   "route_long_name": "Sziksósfürdő / Mars tér / Szőreg",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 53,
   "agency_id": 1,
   "route_short_name": "71A",
   "route_long_name": "Mars tér / Marostő, Katalin utca",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 54,
   "agency_id": 1,
   "route_short_name": "72A",
   "route_long_name": "ELI lézerközpont / Mars tér / Marostő, Erdélyi tér",
   "route_desc": "ELI lézerközpontba csak munkanapokon közlekedik.",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 55,
   "agency_id": 1,
   "route_short_name": "77Y",
   "route_long_name": "Mars tér / Baktó",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 58,
   "agency_id": 1,
   "route_short_name": "76Y",
   "route_long_name": "Mars tér / Szentmihály",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 59,
   "agency_id": 2,
   "route_short_name": "2K",
   "route_long_name": "Európa liget / Szeged vasútállomás",
   "route_desc": "Karácsonyi különjárat",
   "route_type": 0,
   "route_url": "",
   "route_color": "FFFF00",
   "route_text_color": "000000"
 },
 {
   "route_id": 60,
   "agency_id": 2,
   "route_short_name": "19K",
   "route_long_name": "Makkosház / Széchenyi tér",
   "route_desc": "Karácsonyi különjárat",
   "route_type": 11,
   "route_url": "",
   "route_color": "00CC00",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 61,
   "agency_id": 1,
   "route_short_name": "72K",
   "route_long_name": "Mars tér / Marostő, Erdélyi tér",
   "route_desc": "Karácsonyi különjárat",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 62,
   "agency_id": 1,
   "route_short_name": "73K",
   "route_long_name": "Széchenyi tér / Tápé",
   "route_desc": "Karácsonyi különjárat",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 63,
   "agency_id": 1,
   "route_short_name": "74K",
   "route_long_name": "Széchenyi tér / Kecskéstelep",
   "route_desc": "Karácsonyi különjárat",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 64,
   "agency_id": 1,
   "route_short_name": "77K",
   "route_long_name": "Széchenyi tér / Baktó",
   "route_desc": "Karácsonyi különjárat",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 65,
   "agency_id": 1,
   "route_short_name": "40C",
   "route_long_name": "Tarján, Víztorony tér / Szegedi Olimpiai Központ",
   "route_desc": "A járatok igénybevétele díjmentes.",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 66,
   "agency_id": 2,
   "route_short_name": "4V",
   "route_long_name": "Anna kút / Kecskés",
   "route_desc": "villamospótló",
   "route_type": 11,
   "route_url": "",
   "route_color": "FFFF00",
   "route_text_color": "000000"
 },
 {
   "route_id": 68,
   "agency_id": 1,
   "route_short_name": "74",
   "route_long_name": "Tápé / Mars tér / Gyálarét",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 69,
   "agency_id": 1,
   "route_short_name": "74Y",
   "route_long_name": "Tápé / Mars tér / Gyálarét",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 70,
   "agency_id": 1,
   "route_short_name": "74A",
   "route_long_name": "Mars tér / Gyálarét",
   "route_desc": "",
   "route_type": 3,
   "route_url": "",
   "route_color": "0000FF",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 74,
   "agency_id": 3,
   "route_short_name": "1",
   "route_long_name": "Szeged / Hódmezővásárhely",
   "route_desc": "",
   "route_type": 109,
   "route_url": "",
   "route_color": "F6AA1D",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 75,
   "agency_id": 2,
   "route_short_name": "6",
   "route_long_name": "Vértói út / Újszeged, Gyermekkórház",
   "route_desc": "",
   "route_type": 11,
   "route_url": "",
   "route_color": "00CC00",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 76,
   "agency_id": 2,
   "route_short_name": "9",
   "route_long_name": "Lugas utca / Bakay Nándor utca",
   "route_desc": "",
   "route_type": 11,
   "route_url": "",
   "route_color": "00CC00",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 77,
   "agency_id": 3,
   "route_short_name": "1A",
   "route_long_name": "Szeged vasútállomás / Rókus vasútállomás",
   "route_desc": "",
   "route_type": 109,
   "route_url": "",
   "route_color": "F6AA1D",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 78,
   "agency_id": 2,
   "route_short_name": "3V",
   "route_long_name": "Anna-kút / Vadaspark",
   "route_desc": "villamospótló",
   "route_type": 11,
   "route_url": "",
   "route_color": "FFFF00",
   "route_text_color": "000000"
 },
 {
   "route_id": 79,
   "agency_id": 2,
   "route_short_name": "3FV",
   "route_long_name": "Anna-kút / Fonógyári út",
   "route_desc": "villamospótló",
   "route_type": 11,
   "route_url": "",
   "route_color": "FFFF00",
   "route_text_color": "000000"
 },
 {
   "route_id": 80,
   "agency_id": 2,
   "route_short_name": "1-2",
   "route_long_name": "Anna-kút / Szeged vasútállomás",
   "route_desc": "pótlóbusz",
   "route_type": 11,
   "route_url": "",
   "route_color": "00CC00",
   "route_text_color": "FFFFFF"
 },
 {
   "route_id": 81,
   "agency_id": 3,
   "route_short_name": "VP",
   "route_long_name": "Szeged vasútállomás / Hódmezővásárhely vasútállomás",
   "route_desc": "vonatpótló",
   "route_type": 3,
   "route_url": "",
   "route_color": "F6AA1D",
   "route_text_color": "FFFFFF"
 }
]